name: Test

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os.runner }}

    strategy:
      matrix:
        os:
          - runner: windows-latest
          - runner: ubuntu-latest
          - runner: macos-latest
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          submodules: true

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: .\build.bat

      - name: Build on Linux/MacOS
        if: runner.os != 'Windows'
        run: ./build.sh

      - name: Test
        working-directory: build
        run: ctest --output-on-failure
